/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaExerciciosDio;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;

class AppTest {
    @Test
    void nomeTest(){
        assertEquals("Paulo Nogueira tem 24 anos de idade", LoopNomes.mensagem("Paulo Nogueira", 24));
    }

    // teste para loop de notas

    @Test
    void notasSemErros(){
        //teste que não entra no while loop, por isso passa.
        ByteArrayInputStream in = new ByteArrayInputStream("5".getBytes());
        boolean notHaveError;
        try {
            notHaveError = true;
            LoopNotas.postNotas(in);
        } catch(Exception e){
            notHaveError = false;
            System.err.println(e);
        }
        assertTrue(notHaveError, "Verificando se há erro no código quando utilizamos um 'input' ficticio");
    }

    @Test 
    void notasComErros(){
        ByteArrayInputStream in = new ByteArrayInputStream("ABC".getBytes());
        boolean haveError;
        try {
            haveError = true;
            LoopNotas.postNotas(in);
        } catch(Exception e){
            haveError = false;
            System.err.println(e);
        }
        assertFalse(haveError, "Verificando se há erro no código quando utilizamos um 'input' ficticio");
    }

    @Test
    void notasErradasECorrigida(){
        ByteArrayInputStream in = new ByteArrayInputStream("-1 12 20 10".getBytes());
        boolean haveError;
        try {
            haveError = true;
            LoopNotas.postNotas(in);
        } catch(Exception e){
            haveError = false;
            System.err.println(e);
        }
        assertTrue(haveError, "Verificando se há erro no código quando utilizamos um 'input' ficticio");
    }

    @Test 
    void notaEntre0e10(){
        assertTrue(LoopNotas.verificaNota(10), "Verificando se há nota entre 0 e 10");
    }
}
